services:
  app:
    image: golang:latest
    container_name: bookit-app-dev
    working_dir: /app
    volumes:
      - ./app:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
      - "${PPROF_PORT:-6060}:6060"
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c "
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go install github.com/air-verse/air@latest &&
      go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest &&
      air
      "

volumes:
  go-mod-cache:
