ALTER TABLE categories ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE types ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE conveniences ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE countries ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS image TEXT;
