ALTER TABLE categories DROP COLUMN IF EXISTS image;
ALTER TABLE types DROP COLUMN IF EXISTS image;
ALTER TABLE conveniences DROP COLUMN IF EXISTS image;
ALTER TABLE countries DROP COLUMN IF EXISTS image;
ALTER TABLE cities DROP COLUMN IF EXISTS image;
